domain: www.test.com

urls: 
  who: /fr-fr/qui-sommes-nous
  fabricantfrancais: /fr-fr/avantages-cuisinella

targetDirectory: d:\temp\shots

fuzziness: 20

screenWidth: 
- 1280
- 800

scriptFilePath: ./example1.ps1

galleryTemplate: ./example1.cshtml