domain: www.test.com

urls: 
  who: /fr-fr/qui-sommes-nous
  fabricantfrancais: /fr-fr/avantages-cuisinella

targetDirectory: d:\temp\domain-#yyyyMMdd-hhmm#

numberOfThreads: 10

screenWidth: 
- 1280
- 800

scriptFilePath: ./example1.ps1