domain: www.test.com

urls: 
  url1: /MyRelativePath1
  url2: /fr-fr/MyRelativePath1

targetDirectory: d:\temp\shots
sourceDirectory: d:\temp\from

fuzziness: 20

highlightColor: FF0000

numberOfThreads: 10

screenWidth: 
- 1280
- 800

scriptFilePath: ./example1.js

galleryTemplate: ./example1.cshtml