sourceDirectory: d:\temp\prod-#yyyyMMdd-hhmm#
targetDirectory: d:\temp\preprod-#yyyyMMdd-hhmm#
resultDirectory: d:\temp\result-#yyyyMMdd-hhmm#

fuzziness: 20

highlightColor: FF0000

numberOfThreads: 1

galleryTemplate: ./Gallery.cshtml
galleryResult: d:\temp\gallery.html