domain: https://www.ma.cuisinella

urls: 
  nouscontacter: /fr-fr/nous-contacter
  fabricantfrancais: /fr-fr/avantages-cuisinella
  histoire: /fr-fr/success-story

targetDirectory: d:\temp\cla-#yyyyMMdd-hhmm#

numberOfThreads: 11

screenWidth: 
- 1280
- 800

scriptFilePath: ./takescreenshot.js

browser: chrome